services:
  app.type.selector.role:
      class: AppBundle\Form\SelectorType\RoleSelectorType
      arguments:
          - '@service_container'
      tags:
          - { name: form.type }
      shared: true

  app.type.selector.product_type:
      class: AppBundle\Form\SelectorType\ProductTypeSelectorType
      arguments:
          - '@service_container'
      tags:
          - { name: form.type }
      shared: true

  app.type.selector.product:
      class: AppBundle\Form\SelectorType\ProductSelectorType
      arguments:
          - '@service_container'
      tags:
          - { name: form.type }
      shared: true

  app.type.selector.user:
      class: AppBundle\Form\SelectorType\UserSelectorType
      arguments:
          - '@service_container'
      tags:
          - { name: form.type }
      shared: true

  app.type.selector.delivery_type:
      class: AppBundle\Form\SelectorType\DeliveryTypeSelectorType
      arguments:
          - '@service_container'
      tags:
          - { name: form.type }
      shared: true